# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/prj/pynq/end/zynq_prj/zynq_prj.srcs/sources_1/bd/system/ip/system_image_process_0_0/system_image_process_0_0.xci
# IP: The module: 'system_image_process_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/prj/pynq/end/zynq_prj/zynq_prj.srcs/sources_1/bd/system/ip/system_image_process_0_0/src/fifo_block_av_gen/fifo_block_av_gen.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_block_av_gen || ORIG_REF_NAME==fifo_block_av_gen} -quiet] -quiet

# IP: d:/prj/pynq/end/zynq_prj/zynq_prj.srcs/sources_1/bd/system/ip/system_image_process_0_0/src/line_shift_register_1/line_shift_register.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==line_shift_register || ORIG_REF_NAME==line_shift_register} -quiet] -quiet

# IP: d:/prj/pynq/end/zynq_prj/zynq_prj.srcs/sources_1/bd/system/ip/system_image_process_0_0/src/fifo_backframe/fifo_backframe.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_backframe || ORIG_REF_NAME==fifo_backframe} -quiet] -quiet

# IP: d:/prj/pynq/end/zynq_prj/zynq_prj.srcs/sources_1/bd/system/ip/system_image_process_0_0/src/fifo_1/fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo || ORIG_REF_NAME==fifo} -quiet] -quiet

# XDC: d:/prj/pynq/end/zynq_prj/zynq_prj.srcs/sources_1/bd/system/ip/system_image_process_0_0/src/fifo_block_av_gen/fifo_block_av_gen.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_block_av_gen || ORIG_REF_NAME==fifo_block_av_gen} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/prj/pynq/end/zynq_prj/zynq_prj.srcs/sources_1/bd/system/ip/system_image_process_0_0/src/fifo_backframe/fifo_backframe.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_backframe || ORIG_REF_NAME==fifo_backframe} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/prj/pynq/end/zynq_prj/zynq_prj.srcs/sources_1/bd/system/ip/system_image_process_0_0/src/fifo_1/fifo.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo || ORIG_REF_NAME==fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: D:/prj/pynq/end/zynq_prj/zynq_prj.srcs/sources_1/bd/system/ip/system_image_process_0_0/system_image_process_0_0.xci
# IP: The module: 'system_image_process_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/prj/pynq/end/zynq_prj/zynq_prj.srcs/sources_1/bd/system/ip/system_image_process_0_0/src/fifo_block_av_gen/fifo_block_av_gen.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_block_av_gen || ORIG_REF_NAME==fifo_block_av_gen} -quiet] -quiet

# IP: d:/prj/pynq/end/zynq_prj/zynq_prj.srcs/sources_1/bd/system/ip/system_image_process_0_0/src/line_shift_register_1/line_shift_register.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==line_shift_register || ORIG_REF_NAME==line_shift_register} -quiet] -quiet

# IP: d:/prj/pynq/end/zynq_prj/zynq_prj.srcs/sources_1/bd/system/ip/system_image_process_0_0/src/fifo_backframe/fifo_backframe.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_backframe || ORIG_REF_NAME==fifo_backframe} -quiet] -quiet

# IP: d:/prj/pynq/end/zynq_prj/zynq_prj.srcs/sources_1/bd/system/ip/system_image_process_0_0/src/fifo_1/fifo.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo || ORIG_REF_NAME==fifo} -quiet] -quiet

# XDC: d:/prj/pynq/end/zynq_prj/zynq_prj.srcs/sources_1/bd/system/ip/system_image_process_0_0/src/fifo_block_av_gen/fifo_block_av_gen.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_block_av_gen || ORIG_REF_NAME==fifo_block_av_gen} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/prj/pynq/end/zynq_prj/zynq_prj.srcs/sources_1/bd/system/ip/system_image_process_0_0/src/fifo_backframe/fifo_backframe.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_backframe || ORIG_REF_NAME==fifo_backframe} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/prj/pynq/end/zynq_prj/zynq_prj.srcs/sources_1/bd/system/ip/system_image_process_0_0/src/fifo_1/fifo.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo || ORIG_REF_NAME==fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
