# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/prj/pynq/zynq_prj/zynq_prj.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_50M_0/system_rst_processing_system7_0_50M_0.xci
# IP: The module: 'system_rst_processing_system7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/prj/pynq/zynq_prj/zynq_prj.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_50M_0/system_rst_processing_system7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_processing_system7_0_50M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/prj/pynq/zynq_prj/zynq_prj.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_50M_0/system_rst_processing_system7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_processing_system7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/prj/pynq/zynq_prj/zynq_prj.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_50M_0/system_rst_processing_system7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_processing_system7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/prj/pynq/zynq_prj/zynq_prj.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_50M_0/system_rst_processing_system7_0_50M_0.xci
# IP: The module: 'system_rst_processing_system7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/prj/pynq/zynq_prj/zynq_prj.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_50M_0/system_rst_processing_system7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_processing_system7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/prj/pynq/zynq_prj/zynq_prj.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_50M_0/system_rst_processing_system7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_processing_system7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/prj/pynq/zynq_prj/zynq_prj.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_50M_0/system_rst_processing_system7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_processing_system7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
